### ISSUE TITLE
Tutorial about CoppeCosenzaR

### ISSUE THREAD

**Issue by pabloberriel90** [ptaranti/coppeCosenzaR#5]
Hello,

I'm just trying to apply de package Coppe Cosenza in some articles at college, so as to understand how it works and if I can use it in my project. 
Although I had found so many good projects and articles using fuzzy logic, I didn't find yet any tutorial which could show step by step how to construct a project or at least an example as guide about it. 

Could you help me with any infomation or example about the using of coppeCosenzaR ?

I have already read the Help from the package however it didn't work well in my case...

So, I thank you in advance and I hope you could give me any help about it!

Warmest regards,

+5521991234300
pabloberriel90@gmail.com

**Comment by ptaranti** [comment]
An article about the package is to be published. For now, the available documentation is on Cran. Specific requests will be referred to the experts on the method (as I did to yours), or answered by me if it is code-related.

Cheers
